import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

const satoshi = localFont({
  src: "/fonts/Satoshi-Variable.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={satoshi.className}>
      <body className="min-h-screen bg-neutral-950 text-gray-900">
        <div className="max-w-7xl mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
